// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: proto/payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RespCode int32

const (
	RespCode_SUCCESS              RespCode = 0
	RespCode_INSUFFICIENT_BALANCE RespCode = 1001
	RespCode_ACCOUNT_NOT_EXIST    RespCode = 1002
	RespCode_DUPLICATE_REQUEST    RespCode = 1003
)

// Enum value maps for RespCode.
var (
	RespCode_name = map[int32]string{
		0:    "SUCCESS",
		1001: "INSUFFICIENT_BALANCE",
		1002: "ACCOUNT_NOT_EXIST",
		1003: "DUPLICATE_REQUEST",
	}
	RespCode_value = map[string]int32{
		"SUCCESS":              0,
		"INSUFFICIENT_BALANCE": 1001,
		"ACCOUNT_NOT_EXIST":    1002,
		"DUPLICATE_REQUEST":    1003,
	}
)

func (x RespCode) Enum() *RespCode {
	p := new(RespCode)
	*p = x
	return p
}

func (x RespCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RespCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_proto_enumTypes[0].Descriptor()
}

func (RespCode) Type() protoreflect.EnumType {
	return &file_proto_payment_proto_enumTypes[0]
}

func (x RespCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RespCode.Descriptor instead.
func (RespCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{0}
}

type PayOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	BizId         string                 `protobuf:"bytes,3,opt,name=bizId,proto3" json:"bizId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderRequest) Reset() {
	*x = PayOrderRequest{}
	mi := &file_proto_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderRequest) ProtoMessage() {}

func (x *PayOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderRequest.ProtoReflect.Descriptor instead.
func (*PayOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PayOrderRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayOrderRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PayOrderRequest) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

type PayOrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayOrderId    string                 `protobuf:"bytes,1,opt,name=payOrderId,proto3" json:"payOrderId,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	CreatedTime   int64                  `protobuf:"varint,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderInfo) Reset() {
	*x = PayOrderInfo{}
	mi := &file_proto_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderInfo) ProtoMessage() {}

func (x *PayOrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderInfo.ProtoReflect.Descriptor instead.
func (*PayOrderInfo) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PayOrderInfo) GetPayOrderId() string {
	if x != nil {
		return x.PayOrderId
	}
	return ""
}

func (x *PayOrderInfo) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PayOrderInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayOrderInfo) GetCreatedTime() int64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

type PayOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrorMsg      *string                `protobuf:"bytes,2,opt,name=errorMsg,proto3,oneof" json:"errorMsg,omitempty"`
	PayOrderInfo  *PayOrderInfo          `protobuf:"bytes,3,opt,name=payOrderInfo,proto3,oneof" json:"payOrderInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderResponse) Reset() {
	*x = PayOrderResponse{}
	mi := &file_proto_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderResponse) ProtoMessage() {}

func (x *PayOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderResponse.ProtoReflect.Descriptor instead.
func (*PayOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PayOrderResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PayOrderResponse) GetErrorMsg() string {
	if x != nil && x.ErrorMsg != nil {
		return *x.ErrorMsg
	}
	return ""
}

func (x *PayOrderResponse) GetPayOrderInfo() *PayOrderInfo {
	if x != nil {
		return x.PayOrderInfo
	}
	return nil
}

type PayOrderQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	BizId         *string                `protobuf:"bytes,2,opt,name=bizId,proto3,oneof" json:"bizId,omitempty"`
	QuerySize     *int32                 `protobuf:"varint,3,opt,name=querySize,proto3,oneof" json:"querySize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderQueryRequest) Reset() {
	*x = PayOrderQueryRequest{}
	mi := &file_proto_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderQueryRequest) ProtoMessage() {}

func (x *PayOrderQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderQueryRequest.ProtoReflect.Descriptor instead.
func (*PayOrderQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PayOrderQueryRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayOrderQueryRequest) GetBizId() string {
	if x != nil && x.BizId != nil {
		return *x.BizId
	}
	return ""
}

func (x *PayOrderQueryRequest) GetQuerySize() int32 {
	if x != nil && x.QuerySize != nil {
		return *x.QuerySize
	}
	return 0
}

type PayOrderQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrorMsg      *string                `protobuf:"bytes,2,opt,name=errorMsg,proto3,oneof" json:"errorMsg,omitempty"`
	PayOrderInfos []*PayOrderInfo        `protobuf:"bytes,3,rep,name=payOrderInfos,proto3" json:"payOrderInfos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderQueryResponse) Reset() {
	*x = PayOrderQueryResponse{}
	mi := &file_proto_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderQueryResponse) ProtoMessage() {}

func (x *PayOrderQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderQueryResponse.ProtoReflect.Descriptor instead.
func (*PayOrderQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{4}
}

func (x *PayOrderQueryResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PayOrderQueryResponse) GetErrorMsg() string {
	if x != nil && x.ErrorMsg != nil {
		return *x.ErrorMsg
	}
	return ""
}

func (x *PayOrderQueryResponse) GetPayOrderInfos() []*PayOrderInfo {
	if x != nil {
		return x.PayOrderInfos
	}
	return nil
}

var File_proto_payment_proto protoreflect.FileDescriptor

const file_proto_payment_proto_rawDesc = "" +
	"\n" +
	"\x13proto/payment.proto\x12\tpaymentpb\"W\n" +
	"\x0fPayOrderRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x14\n" +
	"\x05bizId\x18\x03 \x01(\tR\x05bizId\"\x80\x01\n" +
	"\fPayOrderInfo\x12\x1e\n" +
	"\n" +
	"payOrderId\x18\x01 \x01(\tR\n" +
	"payOrderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x05R\x06userId\x12 \n" +
	"\vcreatedTime\x18\x04 \x01(\x03R\vcreatedTime\"\xa7\x01\n" +
	"\x10PayOrderResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1f\n" +
	"\berrorMsg\x18\x02 \x01(\tH\x00R\berrorMsg\x88\x01\x01\x12@\n" +
	"\fpayOrderInfo\x18\x03 \x01(\v2\x17.paymentpb.PayOrderInfoH\x01R\fpayOrderInfo\x88\x01\x01B\v\n" +
	"\t_errorMsgB\x0f\n" +
	"\r_payOrderInfo\"\x84\x01\n" +
	"\x14PayOrderQueryRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\x12\x19\n" +
	"\x05bizId\x18\x02 \x01(\tH\x00R\x05bizId\x88\x01\x01\x12!\n" +
	"\tquerySize\x18\x03 \x01(\x05H\x01R\tquerySize\x88\x01\x01B\b\n" +
	"\x06_bizIdB\f\n" +
	"\n" +
	"_querySize\"\x98\x01\n" +
	"\x15PayOrderQueryResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1f\n" +
	"\berrorMsg\x18\x02 \x01(\tH\x00R\berrorMsg\x88\x01\x01\x12=\n" +
	"\rpayOrderInfos\x18\x03 \x03(\v2\x17.paymentpb.PayOrderInfoR\rpayOrderInfosB\v\n" +
	"\t_errorMsg*b\n" +
	"\bRespCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x19\n" +
	"\x14INSUFFICIENT_BALANCE\x10\xe9\a\x12\x16\n" +
	"\x11ACCOUNT_NOT_EXIST\x10\xea\a\x12\x16\n" +
	"\x11DUPLICATE_REQUEST\x10\xeb\a2\xa9\x01\n" +
	"\x0ePaymentService\x12C\n" +
	"\bPayOrder\x12\x1a.paymentpb.PayOrderRequest\x1a\x1b.paymentpb.PayOrderResponse\x12R\n" +
	"\rQueryPayOrder\x12\x1f.paymentpb.PayOrderQueryRequest\x1a .paymentpb.PayOrderQueryResponseB\x16Z\x14/paymentpb;paymentpbb\x06proto3"

var (
	file_proto_payment_proto_rawDescOnce sync.Once
	file_proto_payment_proto_rawDescData []byte
)

func file_proto_payment_proto_rawDescGZIP() []byte {
	file_proto_payment_proto_rawDescOnce.Do(func() {
		file_proto_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_proto_rawDesc), len(file_proto_payment_proto_rawDesc)))
	})
	return file_proto_payment_proto_rawDescData
}

var file_proto_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_payment_proto_goTypes = []any{
	(RespCode)(0),                 // 0: paymentpb.RespCode
	(*PayOrderRequest)(nil),       // 1: paymentpb.PayOrderRequest
	(*PayOrderInfo)(nil),          // 2: paymentpb.PayOrderInfo
	(*PayOrderResponse)(nil),      // 3: paymentpb.PayOrderResponse
	(*PayOrderQueryRequest)(nil),  // 4: paymentpb.PayOrderQueryRequest
	(*PayOrderQueryResponse)(nil), // 5: paymentpb.PayOrderQueryResponse
}
var file_proto_payment_proto_depIdxs = []int32{
	2, // 0: paymentpb.PayOrderResponse.payOrderInfo:type_name -> paymentpb.PayOrderInfo
	2, // 1: paymentpb.PayOrderQueryResponse.payOrderInfos:type_name -> paymentpb.PayOrderInfo
	1, // 2: paymentpb.PaymentService.PayOrder:input_type -> paymentpb.PayOrderRequest
	4, // 3: paymentpb.PaymentService.QueryPayOrder:input_type -> paymentpb.PayOrderQueryRequest
	3, // 4: paymentpb.PaymentService.PayOrder:output_type -> paymentpb.PayOrderResponse
	5, // 5: paymentpb.PaymentService.QueryPayOrder:output_type -> paymentpb.PayOrderQueryResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_payment_proto_init() }
func file_proto_payment_proto_init() {
	if File_proto_payment_proto != nil {
		return
	}
	file_proto_payment_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_payment_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_payment_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_proto_rawDesc), len(file_proto_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_proto_goTypes,
		DependencyIndexes: file_proto_payment_proto_depIdxs,
		EnumInfos:         file_proto_payment_proto_enumTypes,
		MessageInfos:      file_proto_payment_proto_msgTypes,
	}.Build()
	File_proto_payment_proto = out.File
	file_proto_payment_proto_goTypes = nil
	file_proto_payment_proto_depIdxs = nil
}
